### ISSUE TITLE
suggests invalid bug URLs for GitLab instances

### ISSUE THREAD

**Issue by jelmer** [jelmer/upstream-ontologist#36]
In https://salsa.debian.org/debian/decopy/-/merge_requests/3, lintian-brush suggests a Bug Database URL that is broken.

I can reproduce this with ``guess-upstream-metadata``:

```
Name: decopy
Repository: https://salsa.debian.org/debian/decopy.git
Homepage: https://salsa.debian.org/debian/decopy
X-Version: 0.2.4.7
X-Summary: Automatic debian/copyright Generator
X-Description: |2-

      Decopy automates writing and updating the debian/copyright file.

      It reads all files in the source tree, analyzes the licenses and copyright
      messages included and generates the corresponding debian/copyright file.
      When the file already exists, decopy parses it to generate a more complete
      output.

X-License: ISC
X-Author:
- !Person
  name: Maximiliano Curia
  email: maxy@debian.org
  url:
Repository-Browse: https://salsa.debian.org/debian/decopy
Bug-Database: https://salsa.debian.org/debian/decopy/issues
Bug-Submit: https://salsa.debian.org/debian/decopy/issues/new
```

However, while the project exists, it does not have issues enabled.
